### ISSUE TITLE
Adding Navbar 

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#1]

**Comment by Jose-Cera** [comment]
How it should be?

**Comment by Kritika30032002** [comment]
> How it should be?

you can use your own creativity.

**Comment by iamatifmoin** [comment]
@Kritika30032002 
I want to work on this issue. 
Please assign it to me.

**Comment by Kritika30032002** [comment]
Okay

**Comment by Kritika30032002** [comment]
@Jose-Cera  Are you working on this issue?

**Comment by Jose-Cera** [comment]
Unfortunately now I'm busy, I can do it the next week.

**Comment by Kritika30032002** [comment]
Then I have to assign who is available now! You can then take another issue!

**Comment by Kritika30032002** [comment]
@iamatifmoin You can start working on it!

**Comment by Riya14-dangra** [comment]
hey @Kritika30032002 Can you please assign me this issue under kwoc2022??

**Comment by Kritika30032002** [comment]
@Riya14-dangra  You can take another issue which is not yet assigned to anyone else or create a new issue.
