### ISSUE TITLE
Enhance The UI of Login and register page

### ISSUE THREAD

**Issue by Ghat0tkach** [Kritika30032002/Top_Secrets#10]
I would love to work for the enhancement of ui .
Following changes i do have in my mind -;
1)make the background look more aesthetic.
2)To add the navbar and footer
3)modify the display of login and register boxes

**Comment by Kritika30032002** [comment]
navbar and footer have been added already

**Comment by Kritika30032002** [comment]
you can work on improving ui but it must look good and attractive.

**Comment by Ghat0tkach** [comment]
> navbar and footer have been added already

but they arent visible on login /register page

**Comment by Kritika30032002** [comment]
when you have forked the repo?

**Comment by Ghat0tkach** [comment]
> when you have forked the repo?
About an hour ago i synced again

**Comment by Kritika30032002** [comment]
Also you can add home button to navbar as when user clicks on register or login , there is no way to come back to home page(current).

**Comment by SomilRathore01** [comment]
Hey @Kritika30032002 can you please assign this issue to me for competing in KWOC 2022.

**Comment by shreyaa-1** [comment]
![Screenshot (1657)](https://user-images.githubusercontent.com/106281193/206956565-621831e3-5efc-48d8-a0e6-fe8aa6aae477.png)

**Comment by SomilRathore01** [comment]
Hey @Kritika30032002 can you please assign this task to me for competing at KWOC 2022.
