### ISSUE TITLE
Redesigning of the website to make it look more appealing and adding more description

### ISSUE THREAD

**Issue by HemantKumar01** [Kritika30032002/Top_Secrets#101]
Currently the website lacks a compelling modern UI/UX . Anyone landing the website is not very likely to login or  register. A complete redesigning of website is needed to make users attached to it.

**Comment by HemantKumar01** [comment]
Also adding description and taglines to landing page itself will make user more easier to understand about it.

**Comment by HemantKumar01** [comment]
I would like to redesign the website completely, with animations

**Comment by Kritika30032002** [comment]
Note: Merge of PR depends on design

**Comment by Kritika30032002** [comment]
program name?

**Comment by HemantKumar01** [comment]
> program name?

Codepeak 2023

**Comment by HemantKumar01** [comment]
I redesigned the website completely. Is it fine?

**Comment by Kritika30032002** [comment]
check feedback on pr @HemantKumar01

**Comment by HemantKumar01** [comment]
I changed the colors #103  . Does it look better now?
