### ISSUE TITLE
Redesigning footer to add Privacy Policy and FAQS options

### ISSUE THREAD

**Issue by aindree-2005** [Kritika30032002/Top_Secrets#102]
- The site would not be trusted unless people are sure that the secrets won't be shared elsewhere. Adding it resolves trust issues for user.
- Additionally, adding Contact Us ,FAQs and QuickLinks makes it look appealing

@Kritika30032002 Can I work on this?

**Comment by jayeshbhole7** [comment]
can we add a chat-bot for faqs??

**Comment by jayeshbhole7** [comment]
if yes i would like to contribute!

**Comment by singhcoder694** [comment]
@Kritika30032002 I would like to work on this issue...
