### ISSUE TITLE
404 page is missing 

### ISSUE THREAD

**Issue by AaadityaG** [Kritika30032002/Top_Secrets#108]
![404](https://github.com/Kritika30032002/Top_Secrets/assets/114663382/9fb4f082-e0ee-4620-8631-cefc75bb4016)

**Comment by AaadityaG** [comment]
Please allow me to work on it

**Comment by YashSachan2** [comment]
Hi @Kritika30032002 Can I work on this issue under Codepeak-23?

**Comment by AaadityaG** [comment]
@YashSachan2 brother you can do it..

**Comment by Yash-Ainapure** [comment]
@Kritika30032002  can i work on it ?

**Comment by Kritika30032002** [comment]
yes

**Comment by Yash-Ainapure** [comment]
@Kritika30032002 
![Screenshot (127)](https://github.com/Kritika30032002/Top_Secrets/assets/136250383/8ea43db5-7416-4f96-a1e0-63247640f97c)
 
Is this ok?
