### ISSUE TITLE
Buttons size and some text's font size is not responsive

### ISSUE THREAD

**Issue by AaadityaG** [Kritika30032002/Top_Secrets#110]
https://github.com/Kritika30032002/Top_Secrets/assets/114663382/0c4be595-a3fc-4d87-bd02-2ed2936151de

**Comment by AaadityaG** [comment]
Allow me to work on it

**Comment by Kritika30032002** [comment]
PR Merge depends on impact of changes

**Comment by AaadityaG** [comment]
Shoul I handle both #109 and #110 together as they are small contris
