### ISSUE TITLE
make an form validation if the fields are not filled.

### ISSUE THREAD

**Issue by NandishM0618** [Kritika30032002/Top_Secrets#115]
![issue18](https://github.com/Kritika30032002/Top_Secrets/assets/100901899/40b983b5-4723-431d-aef8-2c1d8c3d430a)

**Comment by Kritika30032002** [comment]
brief it more

**Comment by NandishM0618** [comment]
When we click on register button without filling the fields it should alerts the message as "please fill the fields first" instead it the above message.

**Comment by NandishM0618** [comment]
@Kritika30032002 correct me if I am wrong

**Comment by Kritika30032002** [comment]
if both empty then it should display "Please fill email and password"
if any one is empty then "Please fill email/Password"


Do these things in both Login and Register page

and also add placeholder to login page

**Comment by NandishM0618** [comment]
Okay

**Comment by Kritika30032002** [comment]
submit video to show working

**Comment by NandishM0618** [comment]
https://github.com/Kritika30032002/Top_Secrets/assets/100901899/bb5e7433-6f3b-45f8-8c2e-fa5f89c5f6e9

**Comment by NandishM0618** [comment]
done #124
