### ISSUE TITLE
website lacks uniformity in terms of its component be it the buttons or page partition , color sync

### ISSUE THREAD

**Issue by shaileshthakur1** [Kritika30032002/Top_Secrets#116]
Actually, I am facing an issue , setting the project locally , 
Help me with local setup video may be or the other way , so that i can work upon 
few of many issues that i witness @Kritika30032002 .

**Comment by Kritika30032002** [comment]
what issue you are facing?

**Comment by YashSachan2** [comment]
@Kritika30032002 can I take on this issue under Codepeak-23

**Comment by Kritika30032002** [comment]
till now facing same?

**Comment by Kritika30032002** [comment]
@shaileshthakur1

**Comment by shaileshthakur1** [comment]
yes @Kritika30032002 I've even Dm'ed you the ss on Discord, you may check the error.

**Comment by Kritika30032002** [comment]
after that few changes were made

fork the repo again and see the steps in updated readme for setup

**Comment by shaileshthakur1** [comment]
okay @Kritika30032002 let me review if its working.
