### ISSUE TITLE
update: Enhance README for easier local setup of project

### ISSUE THREAD

**Issue by SamIsTheFBI** [Kritika30032002/Top_Secrets#118]
## :question: Problem Description

- Currently lots of contributors are confused with setting up of the project. Setup instructions are incomplete & unclear.

## :framed_picture: Proposed Solution

- I can help with enhancing the documentation of this project by adding detailed instructions for setting up the project locally.

**Comment by Kritika30032002** [comment]
Also make changes in the code accordingly and try to raise pr as soon as possible.

**Comment by SamIsTheFBI** [comment]
Made PR #120 regarding this issue.
