### ISSUE TITLE
Improve Get In Touch Page Design 

### ISSUE THREAD

**Issue by PSS2134** [Kritika30032002/Top_Secrets#131]
![Screenshot 2023-12-21 153441](https://github.com/Kritika30032002/Top_Secrets/assets/101321904/9ae4cd74-26e4-4ef9-9452-38291ce9d45b)
Changing the form Design by adding image side by side to form and also changing style of form @Kritika30032002

**Comment by Kritika30032002** [comment]
program name?

**Comment by PSS2134** [comment]
Codepeak'23 @Kritika30032002

**Comment by PSS2134** [comment]
Changed Overall Get In Touch Page Design, removed old one + made responsive #136 
![Screenshot 2023-12-22 025239](https://github.com/Kritika30032002/Top_Secrets/assets/101321904/cfb048c7-9c47-4760-a1c9-45d49b0fd301)
@Kritika30032002
