### ISSUE TITLE
Adding delete button to delete a secret

### ISSUE THREAD

**Issue by Sami3160** [Kritika30032002/Top_Secrets#135]
here is preview after implementing my previous issue #134 
![Screenshot (172)_LI](https://github.com/Kritika30032002/Top_Secrets/assets/110652247/5c5c4e82-f28c-4b54-b5ef-3e9306ead10d)
well the color won't be yellow, I'll make it match to theme...

**Comment by Kritika30032002** [comment]
no delete option
