### ISSUE TITLE
google signin still not working

### ISSUE THREAD

**Issue by Yash-Ainapure** [Kritika30032002/Top_Secrets#146]
![Screenshot (145)](https://github.com/Kritika30032002/Top_Secrets/assets/136250383/0042e509-9688-4a6a-8a91-39c112306057)

@Kritika30032002 
# Solution: 
* The problem is that the url of website we gave in code and url submited on google cloud console page is not matching.just update the url in google cloud console and it will start working fine

**Comment by Kritika30032002** [comment]
dm me on discord with this issue
