### ISSUE TITLE
Improve the UI of secrets page

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#150]

**Comment by praptisharma28** [comment]
Assign me @Kritika30032002

**Comment by jinx-vi-0** [comment]
@praptisharma28 are you still working on this issue ?
if not , can you pls assign it to me @Kritika30032002

**Comment by praptisharma28** [comment]
go ahead @jinx-vi-0

**Comment by jinx-vi-0** [comment]
@Kritika30032002 please assign this issue to me

**Comment by jinx-vi-0** [comment]
@Kritika30032002 I have created a pr, please check it.
