### ISSUE TITLE
Align the image on about page

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#151]
Align the image on about page on right side of website on desktop mode
and below content in mobile mode

**Comment by Bayyana-kiran** [comment]
Hey @Kritika30032002 can u assign me under iwoc ?
Approach: changing the alignments of pic as I done to the to do list alignments  in  ur previous repo

**Comment by Kritika30032002** [comment]
issues are assigned on first come first serve basis

**Comment by Jenis07** [comment]
Desktop mode:
![image](https://github.com/Kritika30032002/Top_Secrets/assets/100338684/f2c76454-d6cb-4ea7-bba7-f4bcec40aa68)
mobile mode:
![image](https://github.com/Kritika30032002/Top_Secrets/assets/100338684/e566d993-d119-4f43-95cb-b9638386331a)
anything change?

**Comment by Kritika30032002** [comment]
no

**Comment by Jenis07** [comment]
Ma'am this issue is already solved.. when i have pulled the repo that is alredy as you mentioned in the issue so what's i have to do now?

**Comment by Kritika30032002** [comment]
i couldn't see it

**Comment by jinx-vi-0** [comment]
please assign this issue to me.

**Comment by jinx-vi-0** [comment]
Hello @Kritika30032002 I have created a pr, please check it and let me know the feedback
