### ISSUE TITLE
[BUG]: Dark Mode is not Applied to Contact Form

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Kritika30032002/Top_Secrets#157]
Dark Mode is not Applied to Contact Form

![image](https://github.com/Kritika30032002/Top_Secrets/assets/140608790/6de61d29-84f8-4b35-aa1b-f234227694bf)

![image](https://github.com/Kritika30032002/Top_Secrets/assets/140608790/6c132a66-eb93-4e28-ae5a-8f989067edb0)

**Comment by JiyaGupta-cs** [comment]
@Kritika30032002 Please assign me this issue under IWOC

**Comment by adi-exe** [comment]
@JiyaGupta-cs are you still working on this issue ?
if not , can you pls assign it to me @Kritika30032002 .

**Comment by JiyaGupta-cs** [comment]
@adi-exe You can go ahead
I'm not working on it

**Comment by Kritika30032002** [comment]
@adi-exe  also check its functionality

**Comment by adi-exe** [comment]
@Kritika30032002  the PR is showing 
"Error: PR title does not conform to the required format."

what is the format of title ?

**Comment by JiyaGupta-cs** [comment]
@adi-exe Give proper commit message like "fix: Added Dark Mode to Contact Form"
Moreover follow this for your PR TITLE also

**Comment by adi-exe** [comment]
@JiyaGupta-cs thanks ! it worked
