### ISSUE TITLE
Adding Scroll to Top Button

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#16]

**Comment by dikshapadi** [comment]
@Kritika30032002 Hello Kritika , can you assign this task to me?
Thank you

PS- Could you please mention where the scroll to top button must be added,in which web page i mean

**Comment by Kritika30032002** [comment]
secrets page

**Comment by SattyamSamania** [comment]
Hey @Kritika30032002 can I work on  this and where to add scroll to top button?

**Comment by Kritika30032002** [comment]
On the secrets page(where secrets are being submitted)

**Comment by iamatifmoin** [comment]
@Kritika30032002 
Can i work on this since the PR has not been made till now?

**Comment by Kritika30032002** [comment]
@SattyamSamania R U Working?

**Comment by SattyamSamania** [comment]
> @SattyamSamania R U Working?
@Kritika30032002 give me time till tomorrow after that you can assign to someone else.

**Comment by SattyamSamania** [comment]
> @SattyamSamania R U Working?
@Kritika30032002 you can assign to someone else this issue.
