### ISSUE TITLE
[BUG] Missing Register /Login Button in Mobile NavBar

### ISSUE THREAD

**Issue by jiveshkalra** [Kritika30032002/Top_Secrets#166]
### Description

 If a person is using the website on mobile , then they dont get the option to login/register and can only see home,about  and contact . which makes this site of no use on mobile phones and smaller screens 

### Screenshots
 
![image](https://github.com/Kritika30032002/Top_Secrets/assets/127482713/ca5092e8-1e1f-4d27-87f0-89de959bd3e1)

### What browser are you seeing the problem on?
Brave (Chromium)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)

**Comment by Kritika30032002** [comment]
login and register buttons are present in center of screen
