### ISSUE TITLE
[BUG] <Contact form not working>

### ISSUE THREAD

**Issue by jinx-vi-0** [Kritika30032002/Top_Secrets#167]
### Description

There is an issue with the contact form – it does not submit successfully after clicking the submit button.

### Screenshots

<img width="943" alt="image" src="https://github.com/Kritika30032002/Top_Secrets/assets/120160355/f1e0e998-662f-4c08-bbab-326c5c13be85">

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)

**Comment by Kritika30032002** [comment]
will be covered in another issue
