### ISSUE TITLE
Making it Responsive

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#17]

**Comment by DHRUVKHANDELWAL00** [comment]
hey @Kritika30032002 , can u work on this?

**Comment by DHRUVKHANDELWAL00** [comment]
hey @Kritika30032002 , can i work on this?

**Comment by Kritika30032002** [comment]
sure! @DHRUVKHANDELWAL00

**Comment by iamatifmoin** [comment]
@Kritika30032002 
If nobody is working on it please assign it to me.

**Comment by DHRUVKHANDELWAL00** [comment]
Hey @Kritika30032002 , you can assign this issue to @iamatifmoin as i have been also assigned another issue which i am working on.

**Comment by Kritika30032002** [comment]
okay @DHRUVKHANDELWAL00 Thanks for informing

**Comment by Kritika30032002** [comment]
@iamatifmoin  You can start working on it
