### ISSUE TITLE
[Other] improving contact us page

### ISSUE THREAD

**Issue by YooAshu** [Kritika30032002/Top_Secrets#176]
### What would you like to share?

the current contact page does not look good improving its style will be better 
![Screenshot 2024-10-01 220400](https://github.com/user-attachments/assets/e4f4ef4d-9047-43c4-9d9b-2b958b3f77de)

### Checklist

- [X] I have checked the existing issues.
- [X] I follow [Contributing Guidelines](https://github.com/Kritika30032002/Top_Secrets/blob/main/contributing.md) of this project.
- [ ] I am a IWOC'24 contributor.

### Code of Conduct

- [X] I agree to follow this project's "[Code of Conduct](https://github.com/Kritika30032002/Top_Secrets/blob/main/code_of_conduct.md)".

**Comment by ShaikHafiza** [comment]
I would like to do this.

**Comment by taansssss** [comment]
@YooAshu  Please assign me this issue. I would like to work on this.
Please assign me under GSSOC'24 extended
