### ISSUE TITLE
[Feature] Introduce a new page so that users can view each other's secrets (without knowing who has posted what secret) 

### ISSUE THREAD

**Issue by kritvisharma** [Kritika30032002/Top_Secrets#178]
### Description

In this feature, we can introduce a new page where we can scroll and view other users' secrets too, making it more interesting. To ensure privacy, usernames of the users may be omitted. 

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)

**Comment by shreyamaheshwari1** [comment]
@kritvisharma kindly assign this to me under the label of gssoc'24 extended and hactoberfest as i have started working on it

**Comment by kritvisharma** [comment]
@shreyamaheshwari1 This isn't my project so I cannot assign it to you and this is a first come, first serve basis assignment 
and according to that it should be assigned to whoever raised the issue. If the issue still remains open then it is assigned to other people who are interested.  The owner of the project will decide to whom to assign.

**Comment by taansssss** [comment]
@shreyamaheshwari1  Please assign me this issue. I would like to work on this.
Please assign me under GSSOC'24 extended and hacktoberfest.

**Comment by Kritika30032002** [comment]
already there
