### ISSUE TITLE
Feature : Forgot Password Functionality

### ISSUE THREAD

**Issue by akash-inft1905** [Kritika30032002/Top_Secrets#179]
### Description

**Issue:**
Currently, there is no option for users to reset their password if they forget it, which can result in frustration and prevent access to their accounts.

**Proposed Solution:**
Implement a "Forgot Password" link on the login page. This link will direct users to a password recovery process where they can enter their registered email address. They will then receive an email with instructions and a secure link to reset their password using **Nodemailer**. This feature will improve user experience and accessibility.

Looking Forward to work on this Issue 

### Checklist

- [ ] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)

**Comment by Trishank-K** [comment]
Hey! If possible I would love to work on this Feature

**Comment by taansssss** [comment]
@akash-inft1905    Please assign me this issue. I would like to work on this.
Please assign me under GSSOC'24 extended

**Comment by ekayZ7875** [comment]
Hello @akash-inft1905 l i would like to work upon this issue.Please assign it to me.
