### ISSUE TITLE
Adding Footer

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#2]

**Comment by iamatifmoin** [comment]
@Kritika30032002 
I want to work on this issue. 
Please assign it to me.

**Comment by Kritika30032002** [comment]
Okay

**Comment by Kritika30032002** [comment]
This is the link to my socials
https://linktr.ee/kritika_gupta

**Comment by Riya14-dangra** [comment]
hey @Kritika30032002 Can you please assign me this issue under kwoc2022??

**Comment by Kritika30032002** [comment]
@Riya14-dangra  You can take another issue which is not yet assigned to anyone else or create a new issue.
