### ISSUE TITLE
Password crediability

### ISSUE THREAD

**Issue by codesmith25103** [Kritika30032002/Top_Secrets#29]
As many website has rule that user must have 8 character in password, containing at least one uppercase letter, one lowercase letter, one number and one special character. These rule provide security to user's password and they are hard to crack. 
Our website does not have this feature. Please assign me this issue so I could work on it.

**Comment by RonitBaranwal** [comment]
Is this issue open??
I am trying to work on it .

**Comment by Kritika30032002** [comment]
yes

**Comment by RonitBaranwal** [comment]
I made pr but don't know why am I getting merging blocked message .
It would be very nice if anyone could help me sort it out.

**Comment by Kritika30032002** [comment]
okay let me see
