### ISSUE TITLE
improve ui of website

### ISSUE THREAD

**Issue by Janhvi52** [Kritika30032002/Top_Secrets#35]
hey can i work under this

**Comment by Ankita0125** [comment]
can you assign me this @Kritika30032002

**Comment by Kritika30032002** [comment]
@Janhvi52  R U Working?

**Comment by Janhvi52** [comment]
> @Janhvi52  R U Working?

Yeah I'm, I've my exams till Wednesday, after that I'll make the pr!

**Comment by Kritika30032002** [comment]
okay

**Comment by iamatifmoin** [comment]
@Kritika30032002 
This issue is the same as issue #10 

If nobody is working on this, could you assign it to me?
Also, please close the other one.

**Comment by iamatifmoin** [comment]
@Kritika30032002 
Can you suggest some changes you want me to implement?

**Comment by iamatifmoin** [comment]
@Kritika30032002 
If you recommend more changes, I can implement them in a new PR after this.
