### ISSUE TITLE
Improving the documentation for better understanding of new users.

### ISSUE THREAD

**Issue by Aryan8445** [Kritika30032002/Top_Secrets#37]

**Comment by chandakanup** [comment]
Hey @Kritika30032002  can you assign this task to me as well.

**Comment by Kritika30032002** [comment]
@Aryan8445 R U working on this?

**Comment by Aryan8445** [comment]
I was going to start working on it tonight but it's fine you can assign it to @chandakanup.

**Comment by Kritika30032002** [comment]
ok

**Comment by GauravGupta993** [comment]
Hi @Kritika30032002, I would like to work on this issue. Please assign this issue to me.

**Comment by singhcoder694** [comment]
@Kritika30032002 Please assign this to me.....

**Comment by singhcoder694** [comment]
@Kritika30032002 it is not Updated Yet, I guess...??
