### ISSUE TITLE
Adding Edit and Delete Option 

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#4]

**Comment by SattyamSamania** [comment]
Hey @Kritika30032002 can you please explain what to do in this issue so that I can work on this

**Comment by Kritika30032002** [comment]
okay

**Comment by Kritika30032002** [comment]
it must be present only on secrets page

**Comment by Kritika30032002** [comment]
it is similar to what we do to a to do list that we can edit or delete tasks, similarly here we can provide user to edit or delete the secrets

**Comment by rithikrajyt** [comment]
hey @Kritika30032002 ,  I want to work on this issue. Can you please assign me??

**Comment by Kritika30032002** [comment]
@SattyamSamania Are you working on this issue?

**Comment by SattyamSamania** [comment]
> @SattyamSamania Are you working on this issue?
> 

@Kritika30032002 you can assign @rithikrajyt

**Comment by musavveer** [comment]
If no one is working assign this issue to me..

**Comment by Kritika30032002** [comment]
@rithikrajyt Are u working on this?

**Comment by fjuren** [comment]
hi @Kritika30032002, this issue isn't quite ready to be worked if I'm understanding the task. I'm assuming you would like to create edit and delete functionality for secrets once they are created by a registered user, however account registration and creating users in the db isn't finished. Looking at the secrets.ejs, it's dependent on having accounts created. I suggest putting this issue on hold until authentication is done with user data created.

**Comment by Yash-Ainapure** [comment]
@Kritika30032002  as of now the website is fully functional , so this issue can be removed from onhold tag 
also I would like to take this task.
