### ISSUE TITLE
hover effect added

### ISSUE THREAD

**Issue by weberankit** [Kritika30032002/Top_Secrets#43]
changes the hover color effect of the button
![Screenshot (14762)](https://user-images.githubusercontent.com/94105514/216749721-564a251e-7ae6-4838-980e-95877e7dec60.png)

**Comment by ironman32022** [comment]
hey hi i have came over your project and i like to fix this issue if you **assign me** i would like to  work and like to contribute to this

**Comment by Pritam1136** [comment]
you can assign this issue to me.

**Comment by Hackeries** [comment]
i want to work please assign me issues

**Comment by Tonystark121** [comment]
Hi @Kritika30032002 I would like to contribute to this issue; pls assign me

**Comment by Touseef-md** [comment]
Hey, I would like to work on this.

**Comment by Kritika30032002** [comment]
@Tonystark121 are you working on this?

**Comment by singhcoder694** [comment]
@Kritika30032002 if @Tonystark121 is not available I can work on this...

**Comment by Kritika30032002** [comment]
Issues are assigned on first come first serve 
if @Tonystark121  is not available then @Touseef-md  will get the chance to work on this issue.
