### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Pritam1136** [Kritika30032002/Top_Secrets#45]
![Screenshot 2023-05-23 154512](https://github.com/Kritika30032002/Top_Secrets/assets/126561455/24a3007f-d977-4771-ad1b-70d315f768b5)

**Whenever I navigate from one file to another file (eg- header.ejs  to footer.ejs) app crashes.**

**Comment by Kritika30032002** [comment]
Follow the steps written in readme
