### ISSUE TITLE
comment all console.log

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#57]

**Comment by Pinaka-Pani-18** [comment]
Sure, I can work on this issue, could you please assign me ?

**Comment by Kritika30032002** [comment]
only 1 issue can be assigned at a time to contributor
after its completion you can get this assigned if till then it's not assigned to anyone

**Comment by RonitBaranwal** [comment]
Can I get assigned for this one ??

**Comment by Tonystark121** [comment]
Hi @Kritika30032002 I would like to contribute to this issue; pls assign me

**Comment by Kritika30032002** [comment]
@Tonystark121  Are you working on this?
