### ISSUE TITLE
solve the error in login with google and facebook

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#58]

**Comment by Pinaka-Pani-18** [comment]
I would like to work on this issue, could you please assign me ?

**Comment by JAYBORICHA07** [comment]
If the issue is still open i can work on it so please assign me the issue I fit is open

**Comment by SamIsTheFBI** [comment]
Hi

I can solve this issue. If it is still open, I would like to be assigned & work on it under <kbd> Codepeak23 </kbd>.

**Comment by Kritika30032002** [comment]
@JAYBORICHA07  Are you working on it?

**Comment by JAYBORICHA07** [comment]
Yes will do a pr soon

**Comment by Kritika30032002** [comment]
Okay

Under program name?

**Comment by Kritika30032002** [comment]
@JAYBORICHA07  Do the pr by today, otherwise it will be assigned to someone else

**Comment by avinasharex** [comment]
You haven't assigned me that task yet on github.Then without assigning me
how I should know I have solved the task.

**Comment by JAYBORICHA07** [comment]
@Kritika30032002 can't produce a google login error in my local host it is running completely fine if you have a screenshot of the error it might be helpful. (I think the error would be in the generation of the client id and secrets redirect URL)

and Currently not able to generate Facebook client id and secret so I need some more time if possible for that

Thank you.

**Comment by SamIsTheFBI** [comment]
Hey @JAYBORICHA07 here's a screenshot of the error. Upon selecting a Google account, this shows up on the browser screen.

![image](https://github.com/Kritika30032002/Top_Secrets/assets/70562711/a854e764-8a0d-4852-a623-103a42536901)

You won't see it on when running locally because the callback URL is same in that case. If you can still fix it, have a look at the code again.

**Comment by JAYBORICHA07** [comment]
okay doing it

**Comment by Kritika30032002** [comment]
@JAYBORICHA07  If you need any help you can ask freely from anyone. and Try to raise PR as soon as possible.


Thanks @SamIsTheFBI  For understanding and helping others. Great work!

**Comment by Yash-Ainapure** [comment]
Heyy @JAYBORICHA07 , are you working on it ? Otherwise please assign me this issue @Kritika30032002 .

**Comment by SamIsTheFBI** [comment]
Hey @Kritika30032002 

It would be nice if you could you merge #120 to update the codebase before I merge any changes regarding this issue, since it makes some changes in app.js file, which could possibly fix this current issue.
