### ISSUE TITLE
Adding Scroll to top Button

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#6]

**Comment by mritul** [comment]
Hi @Kritika30032002 ! Can I be assigned to this issue once the required details are putting when the coding period begins ?

**Comment by Kritika30032002** [comment]
Done!

**Comment by mritul** [comment]
Thanks :)

**Comment by SattyamSamania** [comment]
Hey @Kritika30032002 I can make scroll to top button using JS. Can you please assign this to me.

**Comment by Kritika30032002** [comment]
@mritul Are you working on this?

**Comment by mritul** [comment]
Yes i'd be working on this issue. Can I raise a PR on 15th of this month or so?

**Comment by SattyamSamania** [comment]
> @Kritika30032002 Yes, i'd be working on this issue. Can I raise a PR on 15th of this month or so?

I have already one scroll to top button created with JS. If it's urgent I can work on this.

**Comment by mritul** [comment]
> @mritul any reason for this?

@Kritika30032002 We've got our endsems going on... It's still fine if you'd pass this issue on to someone else. I can take an issue that might be free later on

**Comment by Kritika30032002** [comment]
> > @mritul any reason for this?
> 
> @Kritika30032002 We've got our endsems going on... It's still fine if you'd pass this issue on to someone else. I can take an issue that might be free later on

@mritul  Have you started working on this issue or will start after your end sem?

**Comment by Kritika30032002** [comment]
> > @Kritika30032002 Yes, i'd be working on this issue. Can I raise a PR on 15th of this month or so?
> 
> I have already one scroll to top button created with JS. If it's urgent I can work on this.

Its not about urgency, its about I have firstly assigned this issue to @mritul and if he is working then I can't assign this to anyone else.

**Comment by Kritika30032002** [comment]
@SattyamSamania  You can till then work on another issue already assigned to you.

**Comment by mritul** [comment]
> > > @mritul any reason for this?
> > 
> > @Kritika30032002 We've got our endsems going on... It's still fine if you'd pass this issue on to someone else. I can take an issue that might be free later on
> 
> @mritul  Have you started working on this issue or will start after your end sem?

@Kritika30032002 i have to start working after my endsems... I've set up the project for now on my local machine and the problem where login immediately logs out is to be solved

**Comment by Kritika30032002** [comment]
Okay then as you haven't started working on the issue, I am assigning this to @SattyamSamania . You can work on another issue as soon as you got free from your end sem

Is it okay for you? @mritul

**Comment by mritul** [comment]
> Okay then as you haven't started working on the issue, I am assigning this to @SattyamSamania . You can work on another issue as soon as you got free from your end sem
> 
> Is it okay for you? @mritul 

@Kritika30032002 Totally ! I'll work on a different issue later

**Comment by Kritika30032002** [comment]
> > Okay then as you haven't started working on the issue, I am assigning this to @SattyamSamania . You can work on another issue as soon as you got free from your end sem
> > Is it okay for you? @mritul
> 
> @Kritika30032002 Totally ! I'll work on a different issue later

Okay

**Comment by SattyamSamania** [comment]
@Kritika30032002 where should i add icons or gif?

**Comment by Kritika30032002** [comment]
its totally upto you

**Comment by Kritika30032002** [comment]
take reference of already written code
