### ISSUE TITLE
How do you remain anonymous after signing in?

### ISSUE THREAD

**Issue by gekkowrld** [Kritika30032002/Top_Secrets#62]
Sites that provides anonymity like [4chan](https://4chan.org/) don't require signing in to post comments. Can this be possible here so that people don't have to share any info before sharing any secrets. To prevent a spam attack a captcha check can be used.

**Comment by Kritika30032002** [comment]
their details are not displayed on website, the credentials are req to prevent rubbish, illegal things to occur 

th qwner has access to see who has submit what but not other users
