### ISSUE TITLE
registration successful toast notification

### ISSUE THREAD

**Issue by surya-nand** [Kritika30032002/Top_Secrets#69]
1. After registering, a success toast notification and redirecting to login page
2. I tried logging in using wrong password (It's throwing an internal server error)

I can work on this issues

**Comment by Kritika30032002** [comment]
Participant of which program?

**Comment by surya-nand** [comment]
Kwoc

**Comment by Kritika30032002** [comment]
> Hey there are other things I noticed in your code • Backend modularising using mvc architecture • Login alerts for wrong password and wrong user • Removing register and login buttons from navbar after logging in and replacing them with logout button
=
> what do you think?



> Hey there are other things I noticed in your code • Backend modularising using mvc architecture • Login alerts for wrong password and wrong user • Removing register and login buttons from navbar after logging in and replacing them with logout button
> 
> what do you think?

Create separate issues for these
