### ISSUE TITLE
Adding About Page

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#7]

**Comment by MrEngineer500** [comment]
Hey Kritika, can I be assigned this task? I'll start working as soon as further details are provided.

**Comment by Kritika30032002** [comment]
Okay
You can join the discord!

**Comment by Riya14-dangra** [comment]
hey @Kritika30032002 Can you please assign me this issue under kwoc2022??

**Comment by Kritika30032002** [comment]
@Riya14-dangra You can take another issue which is not yet assigned to anyone else or create a new issue.

**Comment by MrEngineer500** [comment]
Heyy,
Sorry but I'm unable to join the discord, it shows an invalid link.

**Comment by Kritika30032002** [comment]
@MrEngineer500  Now try again
