### ISSUE TITLE
Distortion of Buttons on opening two windows side by side on Laptop/PC.

### ISSUE THREAD

**Issue by singhcoder694** [Kritika30032002/Top_Secrets#72]
Whenever we use window feature of spliting tab the code used for button are not behaving properly as they get distorted..... 
Attaching images when used website on split window....

<img width="478" alt="Screenshot 2023-12-07 185832" src="https://github.com/Kritika30032002/Top_Secrets/assets/114601400/79859007-02bd-4609-b572-de08c5d33025">
<img width="441" alt="Screenshot 2023-12-07 191029" src="https://github.com/Kritika30032002/Top_Secrets/assets/114601400/c3c3c074-f7e4-4cce-b2e0-0b4a5a1de071">
<img width="285" alt="Screenshot 2023-12-07 191423" src="https://github.com/Kritika30032002/Top_Secrets/assets/114601400/e1139722-8975-4ca5-a369-d07c6def256c">

These are the images for reference!!!

**Comment by singhcoder694** [comment]
I have also resolved the issue by creation own buttons..... @Kritika30032002 , but I am unable to make a PR as it is saying....
remote: Permission to Kritika30032002/Top_Secrets.git denied to singhcoder694.
fatal: unable to access 'https://github.com/Kritika30032002/Top_Secrets.git/': The requested URL returned error: 403

Please provide help for this....

**Comment by Kritika30032002** [comment]
git remote set-url origin <your forked repo link>  

Run above command in terminal and then commit

**Comment by Kritika30032002** [comment]
mention the program name of your participation!

**Comment by omkarbhale** [comment]
@singhcoder694 you don't have permissions to push to this repository directly. You have to fork this repository, make changes in that, and then make a pull request.
