### ISSUE TITLE
Add a Contact Us page

### ISSUE THREAD

**Issue by Kritika30032002** [Kritika30032002/Top_Secrets#83]

**Comment by Yash-Ainapure** [comment]
Hey @Kritika30032002  I would like to contribute to this issue.
Could you please assign it to me?

**Comment by singhcoder694** [comment]
@Kritika30032002 if @Yash-Ainapure is not available, I can work on this...

**Comment by Yash-Ainapure** [comment]
@singhcoder694  sorry for late but i am working on it sir.

**Comment by singhcoder694** [comment]
Ohhkk, it's fine @Yash-Ainapure 😊

**Comment by Kritika30032002** [comment]
add it with all its functionality @singhcoder694

**Comment by Kritika30032002** [comment]
and responsiveness

**Comment by singhcoder694** [comment]
@Kritika30032002 you labeled it as **Hard** but Points are given on basis of **Medium**....

**Comment by Kritika30032002** [comment]
according to code and changes you have made, I have given points.
