### ISSUE TITLE
Add animation to homepage

### ISSUE THREAD

**Issue by aindree-2005** [Kritika30032002/Top_Secrets#87]
The homepage looks really nice and I was planning to add animations to enhance homepage.

**Comment by Kritika30032002** [comment]
under program name?

**Comment by aindree-2005** [comment]
I am in both kwoc and codepeak

**Comment by Kritika30032002** [comment]
In which you want this to be considered ?

**Comment by aindree-2005** [comment]
> In which you want this to be considered ?

Codepeak
