### ISSUE TITLE
Problem in Authentication through Google Account

### ISSUE THREAD

**Issue by subhadipbhowmik** [Kritika30032002/Top_Secrets#95]
Whenever I tried to register through Google account, I was redirected to localhost:3000. So make sure to change the url after authentication on Google Authentication Providers. Convert localhost:3000 -> https://top-secrets.onrender.com/

Screenshots
<img width="392" alt="Screenshot 2023-12-09 211323" src="https://github.com/Kritika30032002/Top_Secrets/assets/57017965/1e9565f6-e816-4e5d-aab0-5832513e9c6f">

<img width="960" alt="Screenshot 2023-12-09 211538" src="https://github.com/Kritika30032002/Top_Secrets/assets/57017965/9bcff487-041c-449e-8d52-41cc0c6b1e8f">

**Comment by hv65616** [comment]
I want to work on this issue as i have worked on google authentication in my self project. So can you assign me this issue to resolve

**Comment by Kritika30032002** [comment]
someone is already working on this
If he is not able to make pr then u can get that assigned
