### ISSUE TITLE
Code cleanup on About and restructuring of content

### ISSUE THREAD

**Issue by Afterdie** [Kritika30032002/Top_Secrets#97]
Currently the content isnt formatted properly and also there is alot of code commented out in the about page.

**Comment by Afterdie** [comment]
I'd like to work on this issue

**Comment by Kritika30032002** [comment]
@Afterdie  Are you working ?

**Comment by RonitBaranwal** [comment]
Will it be okay if I work on this issue?

**Comment by Yash-Ainapure** [comment]
@Kritika30032002 , I would like to take this issue.

**Comment by Yash-Ainapure** [comment]
the structure of website is looking fine for me, do you need any changes for the structure of folders??

**Comment by RonitBaranwal** [comment]
@Yash-Ainapure Hey , its a request ,you should first ask whether someone else is already working on the mentioned issue then request a pr . Else it would be waste of time for both the ends.

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure Hey , its a request ,you should first ask whether someone else is already working on the mentioned issue then request a pr . Else it would be waste of time for both the ends.

Sorry for that, but the assigned role was given 1 week before. it shouldn't take that much time

**Comment by Yash-Ainapure** [comment]
> > @Yash-Ainapure Hey , its a request ,you should first ask whether someone else is already working on the mentioned issue then request a pr . Else it would be waste of time for both the ends.
> 
> Sorry for that, but the issue shouldn't take that much time to solve. Are you working on it?

**Comment by RonitBaranwal** [comment]
> > @Yash-Ainapure Hey , its a request ,you should first ask whether someone else is already working on the mentioned issue then request a pr . Else it would be waste of time for both the ends.
> 
> Sorry for that sir, but the issue shouldn't take that much time to solve. Are you working on it?

I would have worked on it but was just tangled up in certain task of my own, my friend but its all good lets see if owner merges your then we are good to go . Else I will also have a look into it .
